import React, { useState } from 'react';
import { Sparkles, RefreshCcw } from 'lucide-react';
import { api } from '../services/api';

export const AiAnalysis = ({ fund }) => {
  const [aiAnalyzing, setAiAnalyzing] = useState(false);
  const [aiResult, setAiResult] = useState(null);

  const handleAiAnalyze = async () => {
    setAiAnalyzing(true);
    try {
        const response = await api.post('/analyze', fund);
        setAiResult(response.data);
    } catch (error) {
        console.error("AI Analysis failed", error);
        setAiResult({
            summary: "分析服务暂时不可用，请稍后再试。",
            risk: "未知",
            sector: "未知",
            timestamp: new Date().toLocaleTimeString('zh-CN')
        });
    } finally {
        setAiAnalyzing(false);
    }
  };

  return (
    <div className="bg-gradient-to-br from-indigo-50 to-purple-50 rounded-2xl p-6 border border-indigo-100 relative overflow-hidden">
      <div className="absolute top-0 right-0 p-4 opacity-10">
        <Sparkles className="w-24 h-24 text-indigo-600" />
      </div>
      
      <div className="relative z-10">
        <div className="flex items-center gap-2 mb-4">
          <div className="bg-indigo-600 text-white p-1.5 rounded-lg">
            <Sparkles className="w-5 h-5" />
          </div>
          <h3 className="text-lg font-bold text-indigo-900">AI 智能估值分析</h3>
        </div>

        {!aiResult ? (
          <div className="text-center py-6">
            <p className="text-indigo-700 mb-4 text-sm opacity-80">
              基于持仓结构、板块热度及即时资金流向，生成智能解读。
            </p>
            <button 
              onClick={handleAiAnalyze}
              disabled={aiAnalyzing}
              className="bg-indigo-600 hover:bg-indigo-700 text-white px-6 py-2.5 rounded-full font-medium shadow-lg shadow-indigo-200 transition-all active:scale-95 disabled:opacity-70 disabled:cursor-wait flex items-center justify-center gap-2 mx-auto"
            >
              {aiAnalyzing ? (
                <>
                  <RefreshCcw className="w-4 h-4 animate-spin" /> 正在分析市场数据...
                </>
              ) : (
                '开始生成分析报告'
              )}
            </button>
          </div>
        ) : (
          <div className="bg-white/60 backdrop-blur-sm rounded-xl p-5 border border-indigo-100 text-sm leading-relaxed animate-in fade-in slide-in-from-bottom-2">
            <div className="space-y-3 text-indigo-900">
              <p><strong>📊 走势解读：</strong>{aiResult.summary}</p>
              <p><strong>🌊 板块影响：</strong>{aiResult.sector}</p>
              <p className="flex items-center gap-2">
                <strong>⚠️ 风险提示：</strong>
                <span className="bg-orange-100 text-orange-700 px-1.5 py-0.5 rounded text-xs font-bold">{aiResult.risk}</span>
              </p>
              <div className="text-xs text-indigo-400 mt-2 text-right">
                分析时间: {aiResult.timestamp} · Generated by FundVal AI
              </div>
            </div>
            <button 
              onClick={() => setAiResult(null)}
              className="mt-4 text-xs text-indigo-500 hover:text-indigo-700 underline"
            >
              重新分析
            </button>
          </div>
        )}
      </div>
    </div>
  );
};
